In [5]:
import numpy as np
array1 = np.array([[10, 8], [3, 5]])

In [8]:
array1_inverse = np.linalg.inv(array1)
print("反矩陣: ", array1_inverse)
print("驗證: ", np.matmul(array1, array1_inverse))

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


In [13]:
#特徵值/ 向量
w, v = np.linalg.eig(array1)
#特徵值
print("特徵值:", w)
#特徵向量
print("特徵向量:", v)

特徵值 [13.  2.]
特徵向量 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [15]:
#SVD分解
u, s, vh = np.linalg.svd(array1)
print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
